config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :menu_items
  # get "menu_items", to: "menu_items#index"
  # get "menu_items/new", to: "menu_items#new"
  # get "menu_items/:id", to: "menu_items#show"
  # post "menu_items", to: "menu_items#create"
  # put "menu_items/:id", to: "menu_items#update"
  # get "menu_items/edit/:id", to: "menu_items#edit"
  # delete "menu_items/:id", to: "menu_items#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "admin/menu", to: "admin#menu"

  get "/order/:id", to: "cafe#order", as: "order"

  post "/menu_items/:id/buy", to: "menu_items#buy", as: "buy"
  get "/menu_items/:id/success", to: "menu_items#success", as: "success"
  get "/menu_items/:id/cancel", to: "menu_items#cancel", as: "cancel"

  root to: "menu_items#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord
    has_many :menu_menu_items, dependent: :destroy
    has_many :menu_items, through: :menu_menu_items
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
    attribute :price, default: 0.5
    attribute :quantity, default: 1

    has_many :menu_menu_items, dependent: :destroy
    has_many :menus, through: :menu_menu_items

    has_one_attached :image
end

app/models/menu_menu_item.rb
class MenuMenuItem < ApplicationRecord
  belongs_to :menu
  belongs_to :menu_item
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  after_create :assign_default_role

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def assign_default_role
    self.add_role(:staff)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def menu
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cafe_controller.rb
class CafeController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_menu

  def index
  end

  def order
    render plain: @menu[params[:id].to_sym]
  end

  def set_menu
    @menu = MenuItem.all
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:buy]
  before_action :authenticate_user!, except: [:buy]
  before_action :check_roles, except: [:buy]
  before_action :set_item, only: [:show, :update, :edit, :destroy, :buy]
  before_action :set_menus, only: [:show, :update, :edit, :new]
  
  def index
    @items = MenuItem.order(:item)
  end

  def show
  end

  def create
    item = MenuItem.create(menu_item_params)
    redirect_to menu_item_path(item)
  end

  def new
    @item = MenuItem.new
  end

  def update
    @item.update(menu_item_params)
    redirect_to menu_item_path(@item)
  end

  def edit
  end

  def destroy
    @item.destroy
    redirect_to menu_items_path
  end

  def buy
    p @item
    Stripe.api_key = ENV['STRIPE_API_KEY']
    session = Stripe::Checkout::Session.create({
      payment_method_types: ['card'],
      mode: 'payment',
      success_url: success_url(params[:id]),
      cancel_url: cancel_url(params[:id]),
      line_items: [
        {
          price_data: {
            currency: 'aud',
            product_data: {
              name: @item.item
            },
            unit_amount: (@item.price.to_f * 100).to_i
          },
          quantity: 1
        }
      ]
    })

    render json: session
  end

  def success
    render plain: "Success!"
  end

  def cancel
    render plain: "The transaction was cancelled!"
  end

  private

  def set_menus
    @menus = Menu.all
  end

  def set_item
    @item = MenuItem.find(params[:id])
  end

  def check_roles
    if !(user_signed_in? && current_user.has_role?(:admin))
      flash[:alert] = "You are not authorized to access that page"
      redirect_to root_path
    end
  end

  def menu_item_params
    params.require(:menu_item).permit(:item, :price, :quantity, :image, menu_ids: [])
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cafe_helper.rb
module CafeHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/views/admin/menu.html.erb
<h1>Admin#menu</h1>
<p>Find me in app/views/admin/menu.html.erb</p>

app/views/cafe/index.html.erb
<h1>Welcome to Coder Cafe!</h1>

<table>
    <tr>
        <th>Item</th>
        <th>Price</th>
    </tr>
    <% @menu.each do |menu_item| %> 
    <tr>
        <td><%= link_to menu_item.item.capitalize, order_path(menu_item.item) %></td>
        <!-- <td>$<%= "%.2f" % menu_item.price %></td> -->
    </tr>
    <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cafe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if user_signed_in? %> 
      <h4>
        Welcome, <%= current_user.email %>!
        | <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      </h4>
    <% else %>
      <h4>
        Welcome!
        | <%= link_to 'Login', new_user_session_path %>
        | <%= link_to 'Register', new_user_registration_path %>
      </h4>
    <% end %>
    <nav>
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <% if user_signed_in? && current_user.has_role?(:admin) %>
          <li><%= link_to 'Admin', admin_menu_path, id: 'admin-link' %></li>
        <% end %>
      </ul>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/menu_items/_form.html.erb
<%= form_with model: @item, local: true do |f| %>
<div>
    <%= f.label :item %>
    <%= f.text_field :item %>
</div>
<div>
    <%= f.label :price %>
    <%= f.number_field :price, step: 0.01, min: 0.5 %>
</div>
<div>
    <%= f.label :quantity %>
    <%= f.number_field :quantity, min: 1 %>
</div>
<div>
    <%= f.label :image %>
    <%= f.file_field :image %>
</div>
<div>
    <%= f.label :menus %>
    <%= f.collection_check_boxes :menu_ids, @menus, :id, :title %>
</div>
<div>
    <%= f.submit %>
</div>
<% end %>

app/views/menu_items/create.html.erb
<h1>MenuItems#create</h1>
<p>Find me in app/views/menu_items/create.html.erb</p>

app/views/menu_items/destroy.html.erb
<h1>MenuItems#destroy</h1>
<p>Find me in app/views/menu_items/destroy.html.erb</p>

app/views/menu_items/edit.html.erb
<h1>Edit <%= @item.item %></h1>

<%= render 'form' %>

app/views/menu_items/index.html.erb
<h1>Menu Items</h1>

<table>
    <tr>
        <th>Item</th>
        <th>Price</th>
        <th>Qty</th>
        <th>Actions</th>
    </tr>
    <% @items.each do |item| %>
    <tr>
        <td><%= link_to item.item, menu_item_path(item) %></td>
        <td>$<%= "%.2f" % item.price %></td>
        <td><%= item.quantity.to_i %></td>
        <td><%= link_to "Edit", edit_menu_item_path(item) %></td>
    </tr>
    <% end %>
</table>

app/views/menu_items/new.html.erb
<h1>Create a new menu item</h1>

<%= render 'form' %>

app/views/menu_items/show.html.erb
<h1><%= @item.item %></h1>
<% if @item.image.attached? %>
    <p><%= cl_image_tag(@item.image.key, crop: :scale, width: 100, cloud_name: 'flynnwebdev') %></p>
<% end %>
<h3>$<%= "%.2f" % @item.price %></h3>
<p>Quantity: <%= @item.quantity.to_i %></p>
<hr>
<p><%= link_to "Delete!", menu_item_path(@item), method: :delete, data: { confirm: "Are you sure?" } %></p>
<p><button id="buynow-button">Buy Now!</button></p>

<script src="https://js.stripe.com/v3/"></script>

<script>
    const stripe = Stripe('<%= ENV["STRIPE_PUBLISHABLE_KEY"] %>')
    const buyButton = document.getElementById('buynow-button')

    buyButton.addEventListener('click', function() {
        fetch('<%= buy_path(@item.id) %>', {
            method: 'POST'
        })
        .then(function(response) {
            return response.json()
        })
        .then(function(session) {
            return stripe.redirectToCheckout({ sessionId: session.id })
        })
    })
</script>

app/views/menu_items/update.html.erb
<h1>MenuItems#update</h1>
<p>Find me in app/views/menu_items/update.html.erb</p>